/**
 * Scan agents/<eveAgent>/agent/connections/*.ts and emit a build artifact for serverless
 * (Vercel) where the full repo tree is not available at runtime.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { connectionFilenameToIntegrationId } from "../platform/infrastructure/agents/list-wired-integration-ids.js";

const BACKEND_ROOT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

function wiredIdsForEveAgent(eveAgent: string): string[] {
  const connectionsDir = path.join(
    BACKEND_ROOT,
    "agents",
    eveAgent,
    "agent",
    "connections",
  );
  if (!fs.existsSync(connectionsDir)) return [];
  const ids: string[] = [];
  for (const name of fs.readdirSync(connectionsDir)) {
    if (!/\.tsx?$/.test(name) || name.includes(".test.")) continue;
    ids.push(connectionFilenameToIntegrationId(name));
  }
  ids.sort();
  return ids;
}

function discoverEveAgents(): string[] {
  const agentsRoot = path.join(BACKEND_ROOT, "agents");
  if (!fs.existsSync(agentsRoot)) return [];
  return fs
    .readdirSync(agentsRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) =>
      fs.existsSync(
        path.join(agentsRoot, name, "agent", "connections"),
      ),
    )
    .sort();
}

const eveAgents = discoverEveAgents();
const byEveAgent: Record<string, string[]> = {};
for (const eveAgent of eveAgents) {
  const ids = wiredIdsForEveAgent(eveAgent);
  if (ids.length > 0) byEveAgent[eveAgent] = ids;
}

const outPath = path.join(
  BACKEND_ROOT,
  "platform/infrastructure/agents/wired-integrations.manifest.ts",
);

const body = `/** Generated by scripts/sync-wired-integrations-manifest.ts — do not edit by hand. */

export const WIRED_INTEGRATION_IDS_BY_EVE_AGENT: Readonly<
  Record<string, readonly string[]>
> = ${JSON.stringify(byEveAgent, null, 2)} as const;
`;

fs.writeFileSync(outPath, body, "utf8");
console.log(`Wrote ${outPath} (${eveAgents.length} eve agent dirs scanned)`);
