/**
 * Scan agents/<eveAgent>/agent/connections/*.ts and emit a build artifact for serverless
 * (Vercel) where the full repo tree is not available at runtime.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { connectionFilenameToIntegrationId } from "../platform/infrastructure/agents/list-wired-integration-ids.js";

const BACKEND_ROOT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

function collectConnectionIds(connectionsDir: string): string[] {
  if (!fs.existsSync(connectionsDir)) return [];
  const ids: string[] = [];
  for (const name of fs.readdirSync(connectionsDir)) {
    if (!/\.tsx?$/.test(name) || name.includes(".test.")) continue;
    ids.push(connectionFilenameToIntegrationId(name));
  }
  return ids;
}

function wiredIdsForEveAgent(eveAgent: string): string[] {
  const agentRoot = path.join(BACKEND_ROOT, "agents", eveAgent, "agent");
  const ids = new Set<string>();

  for (const id of collectConnectionIds(path.join(agentRoot, "connections"))) {
    ids.add(id);
  }

  const subagentsDir = path.join(agentRoot, "subagents");
  if (fs.existsSync(subagentsDir)) {
    for (const entry of fs.readdirSync(subagentsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      for (const id of collectConnectionIds(
        path.join(subagentsDir, entry.name, "connections"),
      )) {
        ids.add(id);
      }
    }
  }

  return [...ids].sort();
}

function discoverEveAgents(): string[] {
  const agentsRoot = path.join(BACKEND_ROOT, "agents");
  if (!fs.existsSync(agentsRoot)) return [];
  return fs
    .readdirSync(agentsRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => wiredIdsForEveAgent(name).length > 0)
    .sort();
}

const eveAgents = discoverEveAgents();
const byEveAgent: Record<string, string[]> = {};
for (const eveAgent of eveAgents) {
  const ids = wiredIdsForEveAgent(eveAgent);
  if (ids.length > 0) byEveAgent[eveAgent] = ids;
}

const outPath = path.join(
  BACKEND_ROOT,
  "platform/infrastructure/agents/wired-integrations.manifest.ts",
);

const body = `/** Generated by scripts/sync-wired-integrations-manifest.ts — do not edit by hand. */

export const WIRED_INTEGRATION_IDS_BY_EVE_AGENT: Readonly<
  Record<string, readonly string[]>
> = ${JSON.stringify(byEveAgent, null, 2)} as const;
`;

fs.writeFileSync(outPath, body, "utf8");
console.log(`Wrote ${outPath} (${eveAgents.length} eve agent dirs scanned)`);
