/** Generated by scripts/sync-wired-integrations-manifest.ts — do not edit by hand. */

export const WIRED_INTEGRATION_IDS_BY_EVE_AGENT: Readonly<
  Record<string, readonly string[]>
> = {
  "nova-auditor": [
    "hybrid_search"
  ],
  "omni": [
    "hubspot",
    "hybrid_search",
    "notion",
    "proposal_knowledge",
    "zhipu_web_search"
  ],
  "research": [
    "hubspot",
    "hybrid_search",
    "zhipu_web_search"
  ]
} as const;
